[relay]
syncInterval = 300
updateNetworksInterval = 5
enableEtherFaucet = true
enableRelayMetaTransaction = true
enableDeployIdentity = true

[relay.rpc]
host = "node"
port = 8545
ssl = false

[[relay.delegationFees]]
value = 1
currencyNetwork = "0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221"
